### ISSUE TITLE
`NaN` value when reducing division with custom property

### ISSUE THREAD

**Issue by Semigradsky** [postcss/postcss-calc#44]
https://github.com/MoOx/postcss-cssnext/issues/427

Input:
```css
:root {
    --foo: calc(var(--bar) / 8);
}
```
Output:
```css
:root {
    --foo: NaN;
}
```

**Comment by Semigradsky** [comment]
https://github.com/MoOx/postcss-cssnext/issues/427

**Comment by Semigradsky** [comment]
Fixed in https://github.com/MoOx/reduce-css-calc/commit/483e3557190a767f2db244c3d9e1e00feeacae68

**Comment by francoisromain** [comment]
Hello
I still have this error and I don't understand how I should use `reduce-css-calc` to fix it. Can you help?
